### ISSUE TITLE
Can't compile

### ISSUE THREAD

**Issue by cerupcat** [NoahKamara/DocSee#1]
I'd love to test this out, but the packages are local and therefore this can't compile.

**Comment by NoahKamara** [comment]
Hi, this is still a WiP. I’ve added the dependencies as submodules, but still need to update the navigator index to build the index after a bundle has been added.

Im currently working on it and will send an update when the app is in testable condition (mb today, my tomorrow)

**Comment by NoahKamara** [comment]
you can now try out the bundles that are included in the main bundle. The code adding the bundle provider is at MainView.swift:37 if you want to switch it out for another provider (like just using the filesystem)

**Comment by NoahKamara** [comment]
@cerupcat FYI i've added the interface for to add bundles using an http(s) url

**Comment by cerupcat** [comment]
Amazing. I'll take a look shortly.

Do you have an overall idea of what you're trying to accomplish with
DocSee? What was the reason for making it in the first place? Do you intend
to add more things?
ᐧ
